language: python
python:
    - 2.7
    - 3.4
env:
    - TORNADO_VERSION=4.2 PYTEST_VERSION=2.7.1
    - TORNADO_VERSION=4.2 PYTEST_VERSION=2.6.4
    - TORNADO_VERSION=3.2.2 PYTEST_VERSION=2.6.4
    - TORNADO_VERSION=3.2.2 PYTEST_VERSION=2.5.2
install:
    - pip install -q tornado==$TORNADO_VERSION pytest==$PYTEST_VERSION
    - pip install -e .
    - pip install pytest-cov coveralls
script:
    - py.test --strict --cov=pytest_tornado.plugin --cov-report=term-missing
after_success:
  - coveralls
