language: python
python:
    - 2.7
    - pypy
    - 3.4
env:
    - TORNADO_VERSION=4.0.2
    - TORNADO_VERSION=3.2.2
install:
    - pip install -q tornado==$TORNADO_VERSION
    - python setup.py install
script: py.test
